version: "3.7"
services:
  backend:
    container_name: backend
    image: docker.io/desoprotocol/backend:stable
    command: run
    volumes:
    - db:/db
    ports:
    - 17001:17001
    - 17000:17000
    env_file:
    - dev.env
    expose:
    - "17001"
    - "17000"
  frontend:
    container_name: frontend 
    image: docker.io/desoprotocol/frontend:stable
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    env_file:
    - dev.env
    expose:
    - "8080"
  nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
    depends_on: 
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
volumes:
  db:
